### ISSUE TITLE
Unrealiable flashing with TLSR825xComFlasher

### ISSUE THREAD

**Issue by diggit** [pvvx/TlsrComSwireWriter#10]
Hi,
After flashing ZigbeeTLc into modified ZTH02 using TLSR825xComFlasher, FW did not start. I did verification readout and found out, every first write after sector erase will not succeed. This is not detected by the script. Readout returned 0xFF at be beginning of each sector. Adding 100 ms sleep after `FlashEraseSectors` solved the issue for me. Maybe even less is enough.

USB-AURT chip: CH341 with RX/TX LED on dedicated chip pin (not loading RX line)
resistor: 1k8

**Comment by pvvx** [comment]
This program does not read recorded information, but simply transmits data by controlling the SPI registers on the chip. Reading what is written down requires a lot of extra time.
It is possible to "verify" by specifying the command to read and compare the files.

**Comment by diggit** [comment]
Thanks for the explanation!
I assumed `FlashReady` at least tells whether Flash is read for write after sector erase.

This tool was the easiest solution to flash the ZigbeeTLc FW into my sensors. Yeah, it is not the fastest (Readout of 1M flash takes around 50 minutes) or the most reliable, but easy one. ZigbeeTLc conversion OTAs do nothing in my case, but that is for issue report on ZigbeeTLc...

Goal of my report was to let you know, some extra delay after `FlashEraseSectors` may be necessary for successful flashing.
