### ISSUE TITLE
I can't get thing to even start flashing

### ISSUE THREAD

**Issue by evlo** [pvvx/TlsrComSwireWriter#6]
If I try to start program like this `..\python ComSwireReader825x.py --port COM6 wf 0 Original_OTA_Xiaomi_MHO_C401_v1.0.0_0010.bin` on windows, I do get  `ComSwireReader: error: unrecognized arguments: wf 0 Original_OTA_Xiaomi_MHO_C401_v1.0.0_0010.bin`

even `..\python ComSwireReader825x.py --port COM6 -d wf` does not get recognized as operation

Even the help does skip over sub parsers?!
![image](https://user-images.githubusercontent.com/8813196/206711398-22970a23-414d-4f4e-b791-495fd6d325dd.png)

what am I doing wrong?;

I have tried command line instead of powershell and it is the same

I tried on linux and it is the same, feels like I'm missing some stupid thing
![image](https://user-images.githubusercontent.com/8813196/206715857-9456e8a2-fc3f-4e27-9c5d-036dad7cbf98.png)

**Comment by pvvx** [comment]
ComSwire***Reader***825x.py - does not have a "wr" parameter

**Comment by evlo** [comment]
Yeah that is that stupid thing I was writing about
