### ISSUE TITLE
Bit errors while reading flash

### ISSUE THREAD

**Issue by thxomas** [pvvx/TlsrComSwireWriter#9]
Hello,

Thanks for this RE work, it has been very valuable for my project (reversing hanshow firmware)

I extracted a flash firmware from a TLSR8359 using [TLSR825xComFlasher.py](https://github.com/pvvx/TlsrComSwireWriter/blob/master/TLSR825xComFlasher.py) and noticed strange bit errors in the extracted file.
Same errors happen using [ComSwireReader825x.py](https://github.com/pvvx/TlsrComSwireWriter/blob/master/ComSwireReader825x.py)

After testing, I had to comment this line to keep bitmask at 0x20 in function sws_decode() and this fixed the errors :

https://github.com/pvvx/TlsrComSwireWriter/blob/b08c5ea35fde36316e5d644d45e255bca81f82f6/TLSR825xComFlasher.py#L83

I'm not sure if the bitmask change is intentional after 1st bit or a forgotten debug command or a 835x discrepancy.
However, this info may be useful for somebody.

**Comment by pvvx** [comment]
It depends on the clock frequency
